server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: pim-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 100 # 最大连接数
      max-wait-millis: 1000 # 等待连接获取的最大超时时间
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0
  aop:
    proxy-target-class: true
  # elasticsearch 连接地址
  elasticsearch:
    rest:
      uris:
      - http://10.0.6.190:9200
  mail:
      # 163
      host: smtp.163.com
      port: 465
      username: yimcarson@163.com
      password: 123123
      protocol: smtp
      default-encoding: UTF-8
      properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
          mail.smtp.starttls.required: true
          mail.smtp.socketFactory.port: 465
          mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
          mail.smtp.socketFactory.fallback: false


logging:
    level:
      com.lemon1234.mapper: TRACE
      
# Mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  global-config:    db-config:      id-type: UUID      table-underline: false
      table-prefix: t_pim_
  configuration: 
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
